# Generated by Django 5.1a1 on 2024-06-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theAPI', '0003_rename_applicantincome_approval_applicantincome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='Education',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='Property_Area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10),
        ),
    ]
