# Generated by Django 5.1a1 on 2024-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theAPI', '0004_alter_approval_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='Education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=15),
        ),
    ]
